basePath: /api/v1
host: 192.168.1.100:8010
info:
  contact: {}
  title: Fiber API
  version: 1.0.0
paths:
  /articles:
    get:
      responses: {}
      summary: Get articles
      tags:
      - Article
  /articles/{id}:
    get:
      parameters:
      - description: article id
        in: path
        name: id
        required: true
        type: string
      responses: {}
      summary: Get article by id
      tags:
      - Article
swagger: "2.0"
